Add support to copy sample files

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-# Big Nerd Ranch iOS/Mac Machine Bootstrap Script
 # Heavily based on thoughtbot's laptop script https://github.com/thoughtbot/laptop/blob/master/mac
+
+OSX_BOOTSTRAP=${OSX_BOOTSTRAP:-"$HOME/.osx-bootstrap"}
 
 fancy_echo() {
   local fmt="$1"; shift
@@ -150,71 +151,40 @@ update_homebrew() {
 
   echo "$FUNCNAME: Updating local package repository"
   brew update
-
-  echo "$FUNCNAME: Installing/updating some CocoaPod essentials:"
-  script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-  cat "$script_dir"/Brewfile
-  brew bundle --file="$script_dir/Brewfile" --verbose
-
-  if [[ -r "$HOME/.Brewfile" ]]; then
-    echo "$FUNCNAME: Installing/upgrading formulae listed in $HOME/.Brewfile."
-    brew bundle --global --verbose
-  fi
 }
-
 
 find_latest_ruby() {
   rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//'
 }
 
 
-adopt_latest_ruby() {
-  fancy_echo "$FUNCNAME: Activating rbenv"
-  # shellcheck disable=SC2016
-  append_to_shellrc 'eval "$(rbenv init - --no-rehash)"' 1
-  eval "$(rbenv init -)"
-
-  ruby_version="$(find_latest_ruby)"
-  echo "$FUNCNAME: Latest ruby is $ruby_version."
-
-  if ! rbenv versions | grep -Fq "$ruby_version"; then
-    echo "$FUNCNAME: Ruby $ruby_version is not installed. Installing..."
-    RUBY_CONFIGURE_OPTS=--with-openssl-dir="$HOMEBREW_PREFIX/opt/openssl" \
-      rbenv install -s "$ruby_version"
+clone_repo(){
+  if [ ! -d "$OSX_BOOTSTRAP" ]
+  then
+    git clone -b master https://github.com/austek/osx-bootstrap.git "$OSX_BOOTSTRAP"
   fi
-
-  echo "$FUNCNAME: Setting global and shell Ruby versions to $ruby_version"
-  rbenv global "$ruby_version"
-  rbenv shell "$ruby_version"
-
-  echo "$FUNCNAME: Updating system gems..."
-  gem update --system
-
-  echo "$FUNCNAME: All done. Welcome to the brave new world of Ruby $ruby_version."
 }
 
+install_packages() {
+  brew install git
 
-install_or_update_gem() {
-  if gem list "$1" --installed > /dev/null; then
-    gem update "$@"
-  else
-    gem install "$@"
+  clone_repo
+
+  cd "$OSX_BOOTSTRAP" || (echo "$OSX_BOOTSTRAP couldn't be found exiting" && exit)
+
+  echo "$FUNCNAME: Installing/updating essentials:"
+  cat ./Brewfile
+  brew bundle --file=./Brewfile --verbose
+
+  if [[ "$1" -eq "sample" ]]
+  then
+     cp "$OSX_BOOTSTRAP/sample/.Brewfile" "$OSX_BOOTSTRAP/sample/.bootstrap.local" ~/
   fi
-  rbenv rehash
-}
 
-
-setup_bundler() {
-  local number_of_cores
-  local jobcount
-
-  fancy_echo "$FUNCNAME: Ensuring you have the bundler gem installed. This is used to create reliable, reproducible Ruby gem environments during development. Read more at: http://bundler.io/"
-  install_or_update_gem 'bundler'
-
-  number_of_cores=$(sysctl -n hw.ncpu)
-  jobcount=$((number_of_cores - 1))
-  bundle config --global jobs $jobcount
-  echo "$FUNCNAME: Configured bundler to run up to $jobcount jobs simultaneously, and you're good to go!"
+  if [[ -r "$HOME/.Brewfile" ]]; then
+    echo "$FUNCNAME: Installing/upgrading formulae listed in $HOME/.Brewfile."
+    brew bundle --global --verbose
+  fi
 }
 
 
@@ -230,10 +200,8 @@ main() {
   announce_editing_shell_runconfig
   ensure_homebrew_prefix_usable
   update_homebrew
-  adopt_latest_ruby
-  setup_bundler
+  install_packages "$@"
   run_bootstrap_local
 }
 
-
-main
+main "$@"
